# Generated by Django 2.2.2 on 2019-09-06 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choice',
            new_name='Choices',
        ),
    ]
